/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_gd0dM94Cz",
        "userPoolWebClientId": "4j3imt3grnv8u5d2k2n31ovo6d",
        "authenticationFlowType": "USER_SRP_AUTH"
    },
    "aws_cloud_logic_custom": [
        {
            "name": "PresignedURLHttpAPI",
            "endpoint": "https://if32vp9sxd.execute-api.us-east-1.amazonaws.com",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
